location ~ ^/notification/healthcheck/(live|ready)/ {
    proxy_connect_timeout ${NGINX_NOTIFICATION_HEALTHCHECK_CONNECT_TIMEOUT_MS}ms;
    proxy_read_timeout ${NGINX_NOTIFICATION_HEALTHCHECK_READ_TIMEOUT_MS}ms;

    proxy_pass http://notification-service:3000/;
}

location /notification/api/v1/notifications/batch/ {
    limit_req zone=perip burst=${NGINX_NOTIFICATION_NOTIFICATIONS_BATCH_RATE_LIMIT} nodelay;

    proxy_connect_timeout ${NGINX_NOTIFICATION_NOTIFICATIONS_BATCH_CONNECT_TIMEOUT_MS}ms;
    proxy_read_timeout ${NGINX_NOTIFICATION_NOTIFICATIONS_BATCH_READ_TIMEOUT_MS}ms;

    proxy_pass http://notification-service:3000/notifications/batch/;
}

location /notification/ {
    limit_req zone=perip burst=${NGINX_NOTIFICATION_RATE_LIMIT} nodelay;
    
    proxy_connect_timeout ${NGINX_NOTIFICATION_CONNECT_TIMEOUT_MS}ms;
    proxy_read_timeout ${NGINX_NOTIFICATION_READ_TIMEOUT_MS}ms;

    proxy_pass http://notification-service:3000/;
}

location / {
    return 404;
}