export const DEFAULT_MAX_BATCH_SIZE = 1_000;
export const DEFAULT_BATCH_FLUSH_TIMEOUT_MS = 60_000;
export const CHECK_SHUTDOWN_TIMEOUT_MS = 100;
export const DEFAULT_FLUSH_TIMEOUT_MS = 30_000;
export const DEFAULT_HEALTHCHECK_TIMEOUT_MS = 5_000;
